#!/bin/sh
set -e
export LC_ALL=C

#scripts/fribidi-config
#scripts/fribidi-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
chmod +x scripts/libplacebo-validate
scripts/libplacebo-validate
scripts/libass-config
scripts/libass-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"
scripts/mpv-config
scripts/mpv-build "$@"
