#!/bin/sh
set -e

BUILD="$(pwd)"
echo "############## LIBPLACEBO-CONFIG BUILD DIR: $BUILD ##############"
newline="
"

if test -f "$BUILD"/libplacebo_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/libplacebo_options) "$@"
    unset -v IFS
fi

OPTIONS="-Ddefault_library=static -Dtests=false -Ddemos=false"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/libplacebo

test -d build && OPTIONS="$OPTIONS --wipe"
echo Using libplacebo options: $OPTIONS "$@"
echo Using pkg-config path $PKG_CONFIG_PATH

meson setup build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" $OPTIONS "$@"
